project:
  type: website
  output-dir: docs

website:
  title: "Emily Lombardi"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About
      - href: resume.emilylombardi.spring2025.sweetwheelfarms(1).pdf # providing a relative file path to a pdf will open up a browser-based pdf viewer when clicked
        text: Resume
        target: _blank # opens link (or page) in a new browser tab
      - href: free_for_all_page.qmd
        text: Interests
      - href: projects_page.qmd
        text: Projects

format:
  html:
    theme: style.scss
    toc: true

editor: visual

