project:
  type: website
  output-dir: docs

website:
  title: "chooseyourassignment2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.qmd
        text: resume
      - href: free_for_all_page.qmd
        text: free for all page
      - href: resources.qmd
        text: resources
      - href: about_me.qmd
        text: about me

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

